DATA:
  TRAIN:
    IMG_DIR: 'datasets/ImageNet'

DETECTOR:
  NAME: ['vgg13', 'vgg16', 'vgg19']  # ['vgg13', 'vgg16', 'vgg19', 'res50', 'res101', 'res152', 'incv3', 'mobv2']
  INPUT_SIZE: [224, 224]
  BATCH_SIZE: 1

ATTACKER:
  TYPE: "TA-C"
  EPOCH: 20
  DECAY_EPOCH: 4
  TRAIN_BATCH: 50
  REPEAT: 20
  EVAL_BATCH: 800
  LR: 0.01
  STEP_LR: 0.3
  MOMENTUM: 0.9

  ALPHA: 5
  BETA: 0.000006
  CETA: 0.003
  DELTA: 0.1
  TARGET_LABEL: 920
  DOUBLE_APPLY: False

  PATCH:
    WIDTH: 100
    HEIGHT: 100
    CONTENT: "assets/pikachu.jpg"
    EOT: True
    SCALE: 0.3
    ANGLE: 0.1

EVAL:
  SCALE_EVAL: 0.48
  ANGLE_EVAL: 0.1